POST http://localhost:3000/api/veiculos
Content-Type: application/json

{
    "manufactuer": "Fiat",
    "model": "Strada",
    "licencePlate": "CBA-2255",
    "tickets":[
        
        ]
}

###
GET http://localhost:3000/api/veiculos

###
GET http://localhost:3000/api/veiculos/669fa45fb106b099b8812d29

###
DELETE http://localhost:3000/api/veiculos/669fa45fb106b099b8812d29

###
PUT http://localhost:3000/api/veiculos/669fcdc9dbe1f85f2e32ca23
Content-Type: application/json

{
    "manufactuer": "Fiat",
    "model": "Uno",
    "licencePlate": "CBA-2255",
    "tickets":[
            {
                "id": "669fb3e38cca4780702f113f"
            },
            {
                "id": "669fb5ad7542092efe351c2f"
            }
        ]
}

###
GET http://localhost:3000/api/veiculos/soma/669fcdc9dbe1f85f2e32ca23